AWSTemplateFormatVersion: '2010-09-09'
Description: ClawTrap Honeypot - 10 Fargate containers with public IPs (cheapest config)

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues: [production, staging, development]

  GitHubOrg:
    Type: String
    Default: karpie28
    Description: GitHub organization or username

  GitHubRepo:
    Type: String
    Default: clawtrap
    Description: GitHub repository name

  DesiredCount:
    Type: Number
    Default: 10
    Description: Number of Fargate tasks (each gets a public IP)

  HttpPort:
    Type: Number
    Default: 8443
    Description: HTTP honeypot port

  WsPort:
    Type: Number
    Default: 18789
    Description: WebSocket MCP port

  LogRetentionDays:
    Type: Number
    Default: 90
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365]

Resources:
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub clawtrap-${Environment}-vpc

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub clawtrap-${Environment}-igw

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # Public Subnets (2 AZs)
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub clawtrap-${Environment}-public-1

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub clawtrap-${Environment}-public-2

  # Route Table
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub clawtrap-${Environment}-public-rt

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  # Security Group
  TaskSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub clawtrap-${Environment}-task-sg
      GroupDescription: Security group for ClawTrap Fargate tasks
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref HttpPort
          ToPort: !Ref HttpPort
          CidrIp: 0.0.0.0/0
          Description: HTTP honeypot access
        - IpProtocol: tcp
          FromPort: !Ref WsPort
          ToPort: !Ref WsPort
          CidrIp: 0.0.0.0/0
          Description: WebSocket MCP connections
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub clawtrap-${Environment}-task-sg

  # ECR Repository - using existing repo (created outside CloudFormation)
  # The repo clawtrap-production already exists with images

  # S3 Bucket for Logs
  LogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub clawtrap-${Environment}-logs-${AWS::AccountId}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 30
              - StorageClass: GLACIER
                TransitionInDays: 60
            ExpirationInDays: !Ref LogRetentionDays

  LogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LogsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: EnforceHTTPS
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource:
              - !GetAtt LogsBucket.Arn
              - !Sub ${LogsBucket.Arn}/*
            Condition:
              Bool:
                aws:SecureTransport: 'false'

  # ECS Cluster
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub clawtrap-${Environment}
      CapacityProviders:
        - FARGATE_SPOT
        - FARGATE
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE_SPOT
          Weight: 1
      ClusterSettings:
        - Name: containerInsights
          Value: enabled

  # Task Execution Role
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub clawtrap-${Environment}-task-execution
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  # Task Role (for application permissions)
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub clawtrap-${Environment}-task
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3LogsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource: !Sub ${LogsBucket.Arn}/*
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !GetAtt LogsBucket.Arn

  # GitHub OIDC Provider
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - ffffffffffffffffffffffffffffffffffffffff
      Tags:
        - Key: Name
          Value: github-actions-oidc

  # GitHub Actions Role
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub clawtrap-${Environment}-github-actions
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GitHubOIDCProvider
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${GitHubRepo}:*
      Policies:
        - PolicyName: ECRPush
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: '*'
              - Effect: Allow
                Action:
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ecr:PutImage
                Resource: !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/clawtrap-${Environment}
        - PolicyName: ECSUpdate
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecs:UpdateService
                  - ecs:DescribeServices
                  - ecs:DescribeTasks
                  - ecs:ListTasks
                Resource: '*'
                Condition:
                  ArnLike:
                    ecs:cluster: !GetAtt ECSCluster.Arn
              - Effect: Allow
                Action:
                  - ecs:DescribeClusters
                Resource: !GetAtt ECSCluster.Arn
              - Effect: Allow
                Action:
                  - ec2:DescribeNetworkInterfaces
                Resource: '*'

  # CloudWatch Log Group
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/clawtrap-${Environment}
      RetentionInDays: 7

  # Task Definition - ARM64, minimum resources for cost savings
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub clawtrap-${Environment}
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: '256'
      Memory: '512'
      RuntimePlatform:
        CpuArchitecture: ARM64
        OperatingSystemFamily: LINUX
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: honeypot
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/clawtrap-${Environment}:latest
          Essential: true
          PortMappings:
            - ContainerPort: !Ref HttpPort
              Protocol: tcp
            - ContainerPort: !Ref WsPort
              Protocol: tcp
          Environment:
            - Name: CLAWTRAP_HTTP_PORT
              Value: !Ref HttpPort
            - Name: CLAWTRAP_WS_PORT
              Value: !Ref WsPort
            - Name: CLAWTRAP_S3_BUCKET
              Value: !Ref LogsBucket
            - Name: CLAWTRAP_LOG_BACKEND
              Value: s3
            - Name: NODE_ENV
              Value: production
            - Name: AWS_REGION
              Value: !Ref AWS::Region
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: honeypot

  # ECS Service - multiple tasks with public IPs
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub clawtrap-${Environment}
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: !Ref DesiredCount
      PlatformVersion: LATEST
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref PublicSubnet1
            - !Ref PublicSubnet2
          SecurityGroups:
            - !Ref TaskSecurityGroup
      CapacityProviderStrategy:
        - CapacityProvider: FARGATE_SPOT
          Weight: 1

Outputs:
  GitHubActionsRoleArn:
    Value: !GetAtt GitHubActionsRole.Arn
    Description: IAM Role ARN for GitHub Actions (add to GitHub Secrets as AWS_ROLE_ARN)
    Export:
      Name: !Sub ${AWS::StackName}-GitHubActionsRoleArn

  ClusterName:
    Value: !Ref ECSCluster
    Description: ECS Cluster Name
    Export:
      Name: !Sub ${AWS::StackName}-ClusterName

  ServiceName:
    Value: !GetAtt ECSService.Name
    Description: ECS Service Name

  ECRRepository:
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/clawtrap-${Environment}
    Description: ECR Repository URL
    Export:
      Name: !Sub ${AWS::StackName}-ECRRepository

  LogsBucket:
    Value: !Ref LogsBucket
    Description: S3 Bucket for logs
    Export:
      Name: !Sub ${AWS::StackName}-LogsBucket

  VpcId:
    Value: !Ref VPC
    Description: VPC ID
    Export:
      Name: !Sub ${AWS::StackName}-VpcId

  GetPublicIPsCommand:
    Value: !Sub |
      aws ecs list-tasks --cluster ${ECSCluster} --service-name ${ECSService.Name} --query 'taskArns[]' --output text | tr '\t' '\n' | while read task; do eni=$(aws ecs describe-tasks --cluster ${ECSCluster} --tasks "$task" --query 'tasks[0].attachments[0].details[?name==`networkInterfaceId`].value' --output text); aws ec2 describe-network-interfaces --network-interface-ids "$eni" --query 'NetworkInterfaces[0].Association.PublicIp' --output text; done
    Description: Command to list all public IPs

  RotateIPsCommand:
    Value: !Sub |
      aws ecs update-service --cluster ${ECSCluster} --service ${ECSService.Name} --force-new-deployment
    Description: Command to rotate all public IPs
